version: '3'

services:

  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8000:8000"
    command: /usr/local/bin/gunicorn -w 1 -b :8000 index:server # index.py, variable server (flask server)

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app